version: "3.8"
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - DATABASE_URL=postgres://postgres:password@db/postgres
    command: /bin/sh
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - prod_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
volumes:
  prod_db:
